version: '3.7'
services:


   frontdistributions:
      build:
         context: ./frontdistributions
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes: 
         - "./frontdistributions:/app/"
      

 
   backend:
      build: 
         context: ./backend
         dockerfile: Dockerfile
      ports: 
         - "8080:8080"
      volumes: 
         - "./backend:/app/"
     
        

