version: '3.7'
services:


   frontdistributions:
      build:
         context: ./frontdistributions
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes: 
         - "./frontdistributions:/app/"
      

 
   backend:
      build: 
         context: ./backend
         dockerfile: Dockerfile

      command: python3 manage.py runserver 8000   
      ports: 
         - "8000:8000"
      volumes: 
         - "./backend:/app-dist/"
     
        

